apiVersion: v2
name: frontend-chart
description: Helm chart for the Todo Next.js frontend service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - react
  - todo
  - frontend
