openapi: 3.0.0
info:
  title: ChatKit Endpoint API
  version: 1.0.0
  description: |
    Unified ChatKit endpoint for handling all chat operations including
    sending messages, loading history, and executing widget actions.

    This endpoint follows the ChatKit SDK protocol and is compatible with
    the @openai/chatkit-react frontend component.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /chatkit:
    post:
      summary: ChatKit unified endpoint
      description: |
        Handles all ChatKit operations:
        - Send user message and get agent response
        - Load conversation history
        - Execute widget actions (buttons, forms)

        The request type is determined by the request body structure.
        The response can be either JSON (for non-streaming operations)
        or Server-Sent Events (SSE) for streaming responses.

      operationId: processChatKitRequest

      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SendMessageRequest'
                - $ref: '#/components/schemas/LoadHistoryRequest'
                - $ref: '#/components/schemas/ActionRequest'
            examples:
              sendMessage:
                summary: Send a user message
                value:
                  thread_id: "user_123"
                  message: "Add a task to buy milk"

              loadHistory:
                summary: Load conversation history
                value:
                  thread_id: "user_123"
                  after: null
                  limit: 20

              executeAction:
                summary: Execute widget action
                value:
                  thread_id: "user_123"
                  action:
                    type: "button_click"
                    data:
                      task_id: 456

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONResponse'
              examples:
                historyResponse:
                  summary: History loaded successfully
                  value:
                    items:
                      - id: "msg_001"
                        type: "user_message"
                        content: "Hello"
                        created_at: "2026-02-11T10:00:00Z"
                      - id: "msg_002"
                        type: "assistant_message"
                        content: "Hi! How can I help you?"
                        created_at: "2026-02-11T10:00:01Z"
                    has_more: false

            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream
              examples:
                streamingResponse:
                  summary: Streaming agent response
                  value: |
                    event: text_delta
                    data: {"delta": "I've"}

                    event: text_delta
                    data: {"delta": " added"}

                    event: text_delta
                    data: {"delta": " the task"}

                    event: done
                    data: {"item_id": "msg_003"}

        '400':
          description: Bad request (invalid request format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid request format"
                message: "Missing required field: thread_id"

        '401':
          description: Unauthorized (missing or invalid authentication)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Unauthorized"
                message: "Missing X-User-ID header"

        '404':
          description: Not found (thread or item not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Not found"
                message: "Thread user_123 not found"

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Internal server error"
                message: "Database connection failed"

      security:
        - UserIDHeader: []

components:
  schemas:
    SendMessageRequest:
      type: object
      required:
        - thread_id
        - message
      properties:
        thread_id:
          type: string
          description: Unique thread identifier (typically user_id)
          example: "user_123"
        message:
          type: string
          description: User message text
          example: "Add a task to buy milk"

    LoadHistoryRequest:
      type: object
      required:
        - thread_id
      properties:
        thread_id:
          type: string
          description: Unique thread identifier
          example: "user_123"
        after:
          type: string
          nullable: true
          description: Cursor for pagination (last item ID from previous page)
          example: "msg_042"
        limit:
          type: integer
          default: 20
          minimum: 1
          maximum: 100
          description: Maximum number of items to return
          example: 20
        order:
          type: string
          enum: [asc, desc]
          default: asc
          description: Sort order by created_at timestamp
          example: "asc"

    ActionRequest:
      type: object
      required:
        - thread_id
        - action
      properties:
        thread_id:
          type: string
          description: Unique thread identifier
          example: "user_123"
        action:
          type: object
          required:
            - type
            - data
          properties:
            type:
              type: string
              description: Action type identifier
              example: "button_click"
            data:
              type: object
              description: Action-specific data payload
              example:
                task_id: 456

    JSONResponse:
      type: object
      description: Non-streaming JSON response
      properties:
        items:
          type: array
          description: List of thread items (for history requests)
          items:
            $ref: '#/components/schemas/ThreadItem'
        has_more:
          type: boolean
          description: Whether more items are available for pagination
          example: false

    ThreadItem:
      type: object
      required:
        - id
        - type
        - created_at
      properties:
        id:
          type: string
          description: Unique item identifier
          example: "msg_001"
        type:
          type: string
          enum: [user_message, assistant_message, tool_call]
          description: Item type
          example: "user_message"
        content:
          type: string
          description: Item content (format depends on type)
          example: "Hello"
        created_at:
          type: string
          format: date-time
          description: ISO 8601 timestamp
          example: "2026-02-11T10:00:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
          example: "Not found"
        message:
          type: string
          description: Human-readable error message
          example: "Thread user_123 not found"

  securitySchemes:
    UserIDHeader:
      type: apiKey
      in: header
      name: X-User-ID
      description: |
        User ID for authentication and multi-tenancy isolation.
        In production, this should be extracted from JWT token.

tags:
  - name: ChatKit
    description: ChatKit unified endpoint operations
